import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { instrument_sans } from "./fonts";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("flex justify-center p-8", instrument_sans.variable)}>
        <div className="min-h-screen bg-background font-sans antialiased flex min-h-screen flex-col w-full max-w-3xl">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
